---
new_page_extension: html
auto_deploy: false
admin_path: "/forestry"
webhook_url: 
sections:
- type: document
  path: pages.json
  label: Pages Config
- type: directory
  path: ''
  label: Page Contents
  create: all
  match: pages/**/body.html*
  exclude: pages/**/page.json
  new_doc_ext: html.erb
  templates:
  - static-page
- type: directory
  path: ''
  label: Page Configuration
  create: all
  match: "**/page.json"
  new_doc_ext: json
upload_dir: assets
public_path: "/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
